### ISSUE TITLE
Real-Time replacement for BONUS (an internal system for keeping track of all departures) (chris)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1487]
![image](https://cloud.githubusercontent.com/assets/10079829/18564272/cb363116-7b58-11e6-91af-bf95da17ff2a.png)

**Comment by ronenreinheimer** [comment]
Eventually, I would like there to be a feature that automatically sends a high importance email to handling team & manager if:

1.	The number of people actually booked is under the expected pilgrim number by 95 days prior – prompting review
2.	At any point that the number of people actually booked exceeds the expected number - – prompting review

**Comment by chris206** [comment]
Hi Brad,

No pressure, I know that there are other priorities - but this one would save so much un-necessary work that it is almost crazy.

Just something to think about

**Comment by chris206** [comment]
We had a discussion again about this in the office - Sandy would like to implement this feature as soon as possible.

ADDITIONALLY

Each operator would benefit from this serving as a checklist: keeping track of each group and what was sent/not sent (were ground accommodations confirmed, was flyer prepared, was it sent, etc)

When it comes up, I will try to re-write our requirements so that they are all in one place.

**Comment by bradatkins** [comment]
Here's the first cut, obviously not done but getting there:

https://www.206tours.com/register/admin/reports_bonus.php

**Comment by bradatkins** [comment]
Four new fields:

![image](https://cloud.githubusercontent.com/assets/8440255/21296426/607fa138-c539-11e6-9f43-4571cb76a010.png)

![image](https://cloud.githubusercontent.com/assets/8440255/21296427/63906a38-c539-11e6-887e-b870a7f2514c.png)

![image](https://cloud.githubusercontent.com/assets/8440255/21296428/6669bcf0-c539-11e6-88d2-705764669787.png)

**Comment by chris206** [comment]
Thanks Brad, this is a great first step and is a very important feature.
I have an almost endless list of additional features that can be added - but Sandy's request is the most important one in the short term:

"Is missing the ability to sort,
By agent or date(s)would be the most important"
-Sandy

**Comment by chris206** [comment]
Hi Brad,

We can now sort them to a minimal extent BUT the ability to sort in Excel is much more robust.

for example, in excel, we can select all departures handled by Chris, or all departures with Fr. Calloway, all Tour 111, or all with a certain ground operator. Here we can only make them alphabetical.

Barring the ability to select liek we can in excel, It would be better if we could type in our own, like we can with registered passengers:
![image](https://cloud.githubusercontent.com/assets/22382144/21623484/91361d86-d1d0-11e6-8918-81c31ec74b31.png)

Same with departure date - only in Date order or reverse date order in the DB. In excel we can search by specific month.

**Comment by bradatkins** [comment]
Ah well that's filtering! haha the above message from Sandra said ability to sort by agent/date.

**Comment by chris206** [comment]
Ahh. Thank you for the clarification.

Yes, FILTERING is what we will need. 
I also have an idea to associate Manager in the User CP - so that managers will get important departure updates AND be able to sort which pilgrimages that they are ultimately responsible for. I will create separate enhancement request

**Comment by chris206** [comment]
Is it possible to export BONUS to an excel file until the filter feature is actually built in to the DB?
If so, we may be able to phase out the old system sooner than later

**Comment by bradatkins** [comment]
It's a lot of work to make it exportable. I'd rather focus my efforts on adding the required functionality.

**Comment by chris206** [comment]
ok, perfect. then so be it. We are working on the priority list asap and this will absolutely be on it

**Comment by bradatkins** [comment]
I have added filtering much like the orders page. have a look

![image](https://cloud.githubusercontent.com/assets/8440255/21944913/8ccf86e6-d9a6-11e6-9ea6-de98fe9cf0d7.png)

**Comment by chris206** [comment]
Great!

Can you make filtering NON-case sensitive? Also - it doesnt work for tour code.

Please make the following changes:
1. Include PAST tours as well, searching 2016 netted me 0 results. This is a major feature of DB
2. Do not include cancelled passengers in total; ex: DV031017 only has 15 people registered, but BONUS says 19.
3. For the time being, please don't show land only number - just total pax column
4. Make filtering non-case sensitive for all
5. Switch Doc Status and group code location
6. Fix glitch that doesn't allow search of tour code to work

**Comment by chris206** [comment]
do these passenger totals include those on wait list?

**Comment by bradatkins** [comment]
Yes

**Comment by chris206** [comment]
Hey Brad, this is just a touch-up request, similar to the CAKES file manager fix

Can you create a few rules to alter or change file manager in Tours?:

1. Wherever "Amanda Fortunato" is listed as a file manager, "Bika Stevic" must ALSO be listed.
Also, the inverse must be true; Wherever "Bika Stevic" is listed as file manager, "Amanda Fortunato" must also be listed

2. Wherever Piernha Marc, Donna Strucic, Rinda Kanidinc, Sammie Gough, Melissa Mulligan, or Stefanie Meyer are listed - the should ALL be replaced with ROK Team. Rinda is listed as "ADMIN", the rest users if that makes a difference. Don't do it based on everyone she manages, though.

**Comment by bradatkins** [comment]
Can you do me a favor and grab their UsersID # from this screen?

![image](https://cloud.githubusercontent.com/assets/8440255/23714367/e1a5e4ba-03f6-11e7-988c-9509f17b4e9f.png)

**Comment by chris206** [comment]
Melissa - 84
Piernha - 51
Rinda - 8
Donna - 128
Sammie - 151
Stefanie - 16

**Comment by chris206** [comment]
4 Changes have been requested to layout of BONUS:

1. Alternative WHITE/GREY background (like we have with Registered passengers
2. Abbreviate Departure City to 3 letter IATA code (so JFK instead of New York)
3. This one is more complicated: Only departures with the current year should show up. We need to figure out a way to do this because it is completely pointless for us to see 2016 99% of the time.
4. A jump down feature based on month would be useful. We would still be looking at a complete list of 2017 departures BUT pressing MAY for example would bring us down to the first instance where that month appeared in the return date (so it would pop down to the April 29th to May 10th departure). Alternatively if that didnt work, these month buttons would isolate only departure OR return dates had MAY in it.

**Comment by chris206** [comment]
the purpose of these changes is to overcome objections to using BONUS as the primary tool. People are used to using "Registered Passengers" and like how it looks and functions - even though it is missing considerable amounts of info.

**Comment by chris206** [comment]
4 Changes have been requested to layout of BONUS:

Alternative WHITE/GREY background (like we have with Registered passengers). Easier on our eyes
Abbreviate Departure City to 3 letter IATA code (so JFK instead of New York) - half of the company finds this feature to be useless, half thinks it is imperative and they are both right - so it needs to saty, but take up less space.
This one is more complicated: Only departures with the current year should show up. We need to figure out a way to do this because it is completely pointless for us to see 2016 99% of the time. Maybe, like you did with the zero passengers, we could just put any departures with either 0 passengers OR departure/return dates not in a seperate link (like "0 passengers or prior dates" link)
A jump down feature based on month would be useful. We would still be looking at a complete list of 2017 departures BUT pressing MAY for example would bring us down to the first instance where that month appeared in the return date (so it would pop down to the April 29th to May 10th departure). Alternatively if that didnt work, these month buttons would isolate only departure OR return dates had MAY in it.
the purpose of these changes is to overcome objections to using BONUS as the primary tool. People are used to using "Registered Passengers" and like how it looks and functions - even though it is missing considerable amounts of info.

**Comment by chris206** [comment]
4 Changes have been requested to layout of BONUS:

1. Alternative WHITE/GREY background (like we have with Registered passengers). Easier on our eyes

2. Abbreviate Departure City to 3 letter IATA code (so JFK instead of New York) - half of the company finds this feature to be useless, half thinks it is imperative and they are both right - so it needs to saty, but take up less space.

3. This one is more complicated: Only departures with the current year should show up. We need to figure out a way to do this because it is completely pointless for us to see 2016 99% of the time. Maybe, like you did with the zero passengers, we could just put any departures with either 0 passengers OR departure/return dates not in a seperate link (like "0 passengers or prior dates" link)

4. A jump down feature based on month is necessary. We would still be looking at a complete list of 2017 departures BUT pressing MAY for example would bring us down to the first instance where that month appeared in the return date (so it would pop down to the April 29th to May 10th departure). Alternatively if that didnt work, these month buttons would isolate only departure OR return dates had MAY in it.

The purpose of these changes is to overcome objections to using BONUS as the primary tool. People are used to using "Registered Passengers" and like how it looks and functions - even though it is missing considerable amounts of info.

**Comment by bradatkins** [comment]
Can you please log this as a separate request. Thanks.
