### ISSUE TITLE
DB-- Expiration dates not reflecting correctly (sammie)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1657]
![image](https://cloud.githubusercontent.com/assets/10079829/20489380/698becb2-afd8-11e6-9f6f-0a65e864f83d.png)

**Comment by bradatkins** [comment]
Oddly enough, for whatever the reason, the Invoice was making up the "day" field.

The PAX in this case did not specify the day in their passport expiry date.

I've "fixed" it, so that it won't make up a random date:

![image](https://cloud.githubusercontent.com/assets/8440255/20506030/14687088-b01f-11e6-9408-8c9e3553eb55.png)
