### ISSUE TITLE
Urgent : Pax said she completed order with payment but we dont have it? (sandy)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1690]
![image](https://cloud.githubusercontent.com/assets/10079829/20813139/645d4864-b7e2-11e6-8057-80a6703b2da5.png)

**Comment by bradatkins** [comment]
She didn't complete her order the first time because:

The Credit Card Number supplied in the authorization request appears to be invalid.

The second time because:

The value for the Address1 (ssl_avs_address) field is too long. 30 characters (maximum) are allowed. Your entry contains 33 characters.

I guess BD didn't include my field maxlength's when they created their templates :(

I've corrected this now.
