### ISSUE TITLE
Audit Crashed, Spilled Over into Reservation (Patrick)

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1982]
This audit crashed on "departure city" and seems to have overwritten the departure city entirely.

What they heck?

The destination in "all tours" was left blank as it should have been (I remember that from the last "departure city missing" error)

![image](https://cloud.githubusercontent.com/assets/22382144/24007970/93978b60-0a46-11e7-894b-7e314eaf9be5.png)

**Comment by bradatkins** [comment]
The audit seems fine?

![image](https://cloud.githubusercontent.com/assets/8440255/24010382/14ad5f2a-0a4e-11e7-823c-7fdc8d0b2b9a.png)

**Comment by chris206** [comment]
check his second example 427921
Thats odd, the first one didnt crash - why are the cities not coming up

**Comment by bradatkins** [comment]
OK I see it.

What's happening is this:

All tours by default use a standard list of departures (let's say Departure City #1 through #255 for example)

When a tour is set to have it's own price list for departures, it takes a copy of those departure cities so they can have their own pricing, and gives them a new number #256 to #500 for example)

In some places the DB isn't looking at the proper list and is crashing, so I have to fix them up. Apparently there are a lot of spots as you've seen where this happens. The good news is the fix is simple, just have to find all the holes.

**Comment by bradatkins** [comment]
Fixed the crash

**Comment by chris206** [comment]
all prior records were deleted though. I dont know where they meant to travel from
