### ISSUE TITLE
Paypal payments don't work

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#199]
I tried to make a payment through paypal of $400.  

Forgot my password and when i click on the forgot my pword link it brings me to the below picture.  I typed in the code correctly but it doesn't go through and when i close out that screen and reopen it, the same code is there?!

![image](https://cloud.githubusercontent.com/assets/8440903/6268025/3b397cfe-b817-11e4-854f-e3bafe6e8d0d.png)

So i went to paypal's actual website, changed my pword and went to register again making a deposit via Paypal.  Even though i know my pword now and am typing it in correctly, it's not letting me log in and on the bottom of each page it says Test Site:

![image](https://cloud.githubusercontent.com/assets/8440903/6268483/3ab5f7d6-b81b-11e4-8d8b-ed34f3dd76f3.png)

Did you disable Paypal payments?

Can you please fix them?

**Comment by bradatkins** [comment]
OK it's fixed. My test may look a little weird because I forced the system to only send you $1 (because I wanted to do a live test). I can't tell if you actually received the $1 in paypal or not.  In the DB it'll show as if I sent you $400.

Can you check your paypal?

![image](https://cloud.githubusercontent.com/assets/8440255/7441299/8714e138-f0af-11e4-8706-3dec5ecce766.png)

![image](https://cloud.githubusercontent.com/assets/8440255/7441300/8ae7802c-f0af-11e4-8b15-dcf879d1ccbd.png)

**Comment by ali206** [comment]
Just sent you an email - this woman tried to pay $5,000 via paypal and no payment was actually processed:

![image](https://cloud.githubusercontent.com/assets/8440903/7567423/f0f0f552-f7ca-11e4-8a32-3db26708dc4d.png)
