### ISSUE TITLE
default departure city pilgrimages.com

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#207]
Hi Brad,

I think i have everything set properly in the DB, but I need the dropdown menu to show NY:
http://pilgrimages.com/drvc/wyd

**Comment by bradatkins** [comment]
Unfortunately this isn't possible currently.

The reason being is the DB doesn't currently support Default Departure cities when not using the standard departure city list.

In this case, you've hidden the standard departure cities, and created a new departure city of New York, so that only New York shows (which is OK)

I'll mark this as an enhancement for the future.

**Comment by ronenreinheimer** [comment]
OK thank you, please do.

Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
With some tours, they have customized departure cities (for example http://pilgrimages.com/drvc/wyd/)

Previously you couldn't choose what city you wanted to be the default.

Now you can edit the Tour and select the default

![image](https://cloud.githubusercontent.com/assets/8440255/9431331/fa025456-49dc-11e5-93a0-df91a71bb18d.png)

![image](https://cloud.githubusercontent.com/assets/8440255/9431333/fdf91202-49dc-11e5-9cc0-45d8eb30ad0c.png)

![image](https://cloud.githubusercontent.com/assets/8440255/9431334/025dd666-49dd-11e5-8506-4becee714f3f.png)
