### ISSUE TITLE
CC charged once but posting twice cont'd

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#232]
*(one of the $3898 payments has already been declined)

This client made a payment yesterday somehow of $3898 even though her balance was only $3,484.00.  Somehow 2 payments of $3898 were showing on her invoice, so she thought she was charged twice.  We checked merchant, and the payment only went through once. 

How does this happen?

**Comment by ali206** [comment]
![image](https://cloud.githubusercontent.com/assets/8440903/6512032/f07b7572-c33e-11e4-8b1e-a697744eb20f.png)

**Comment by bradatkins** [comment]
I found where this is happening, but not sure why it was coded like this. This was added by Stavros, and only seems to happen in certain situations.

Since I couldn't figure out why it was done like this, I'm not 100% sure on the fix.

Please keep an eye on CC payments. A small worry is that a CC payment will be made and recorded in the Merchant, but maybe not in the DB. Small risk, but just keep an eye out please.

**Comment by ali206** [comment]
Do you know what the certain situations are that his is happening in?  B/c on our end it just seems completely random.

**Comment by bradatkins** [comment]
I can't say for certain, but it almost looks like when making a payment against an existing order, but to be honest with you the code he wrote made no sense at all.

**Comment by bradatkins** [comment]
OK I fixed it. It looks like when people edited their own PAX record / made a payment at the same time this would happen. I've verified the same is happening with issue #54.
