### ISSUE TITLE
DB too slow 

### ISSUE THREAD

**Issue by milanka206** [206Tours/DB#302]
Brad, I have been getting a lot of pressure from agents that --- DB is just too slow. Especially when entering adding group names it takes them for- ever and then some.

**Comment by bradatkins** [comment]
I've done some investigation and found out that because of the number of records has increased so dramatically, the DB has gotten slower.

For example, here's the number of Orders by year (15,683 total):

Inline image 2

Payments (42,488 total):

Inline image 3

What I've done to hopefully make the majority of the day to day better is split the Orders and Payments screen in two sections:

Inline image 4Inline image 5

You can see there's two views now. My hope is that a lot of the day to day will be in the "Current Year" sections, which will be faster.

For example, historical performance of the All Orders section was about 20-40 seconds to load. Now, the "Current Year" section loads in 1-5 seconds.

I'll continue to monitor the logs, but please let me know how it is.
