### ISSUE TITLE
dept/rtn dates wrong 419143

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#391]
I checked the options in all dept. and they look to be set up correctly but on invoice dates are wrong.

![image](https://cloud.githubusercontent.com/assets/8440903/7816189/d8157c48-039a-11e5-87fd-ee3e57ab5d41.png)

![image](https://cloud.githubusercontent.com/assets/8440903/7816210/edf0f95c-039a-11e5-884f-25078eed731d.png)

**Comment by bradatkins** [comment]
Note the departure date is now correct; however the return date is still wrong because the POST stay is actually marked as PRE

![image](https://cloud.githubusercontent.com/assets/8440255/9027530/d4c11dba-3926-11e5-9cf1-131d130fce5e.png)

![image](https://cloud.githubusercontent.com/assets/8440255/9027532/dd6c24b4-3926-11e5-84c2-a24bd0308477.png)
