### ISSUE TITLE
New Look - Initial Testing - Shore Excursions - need check boxes. (Yaritza) - URGENT

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#720]
Hi Brad,

We need check boxes for shore excursions instead of radio button – so clients can select more than 1 excursion (2 screen shots).

Can you please assist us with this issue.

![image](https://cloud.githubusercontent.com/assets/10079829/12365774/f7d06a62-bba4-11e5-9bdc-c8dd4169be6c.png)

![image](https://cloud.githubusercontent.com/assets/10079829/12365819/3468b100-bba5-11e5-8e34-03a45ad7f951.png)
![image](https://cloud.githubusercontent.com/assets/10079829/12365809/221a2db2-bba5-11e5-937d-5a63381d6fb2.png)

**Comment by bradatkins** [comment]
Hey -

This is because the options are setup as separate options. I've created it the proper way:

![image](https://cloud.githubusercontent.com/assets/8440255/12369936/18278140-bbcf-11e5-91d4-ce6b7d00f7d5.png)


![image](https://cloud.githubusercontent.com/assets/8440255/12369937/1bb6b006-bbcf-11e5-8610-998da7a6ed43.png)

**Comment by bradatkins** [comment]
![image](https://cloud.githubusercontent.com/assets/8440255/12369941/27645d36-bbcf-11e5-8ed5-f7d4cd0dc779.png)
