### ISSUE TITLE
"Oz" still appearing as dept. city -422252

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#769]
![image](https://cloud.githubusercontent.com/assets/8440903/12752774/06cfe9e8-c992-11e5-877f-9d49e4835d28.png)

![image](https://cloud.githubusercontent.com/assets/8440903/12752763/f7e920b6-c991-11e5-972a-14a6528ee5a0.png)

![image](https://cloud.githubusercontent.com/assets/8440903/12752781/1017615c-c992-11e5-833f-025d82c72ec3.png)

**Comment by bradatkins** [comment]
This happens when Departure City is missing from the order (for whatever reason).

The invoice will now show a blank, and the recap will show a note:

![image](https://cloud.githubusercontent.com/assets/8440255/12770094/84ac6630-c9eb-11e5-8cee-605bf3ea345d.png)


![image](https://cloud.githubusercontent.com/assets/8440255/12770091/7fff5a8e-c9eb-11e5-9f39-966d3f440e57.png)
