### ISSUE TITLE
Recap - need to show title ( FR / SR etc) 

### ISSUE THREAD

**Issue by rinda206** [206Tours/DB#97]
Dear Brad,

Since the  recap generates list with names as per name on the passport,  could you please  add a column  “tittle”   which will than pull in  title out of DB .  

We need to  show    “ Fr “  or " Sr" on the recap for an easy identification of  a priest / sister.  

Thank you and have a great weekend. 

Rinda

**Comment by ali206** [comment]
Where does the "Fr" have to be selected to show on the recap?

![image](https://cloud.githubusercontent.com/assets/8440903/5685082/e92a7170-9804-11e4-9fef-9c3a76d9376e.png)

![image](https://cloud.githubusercontent.com/assets/8440903/5685086/ef1528be-9804-11e4-99d6-84c81df5acf0.png)

**Comment by bradatkins** [comment]
Done

![image](https://cloud.githubusercontent.com/assets/8440255/5930541/c0fa405a-a65e-11e4-9b24-e7dfd47cd329.png)

**Comment by ali206** [comment]
I think if names on recaps are to be exported as per names on passports than the above picture is incorrect. 

If you look on Gonzalez's invoice, Dr. and Mr. do not show in name as per passport section.

Should the "title" of each passenger show in a different column since it's not necessarily their name as per passport?

It's super important not to mix names ups in those terms

**Comment by bradatkins** [comment]
Done 
![image](https://cloud.githubusercontent.com/assets/8440255/8019842/02e86a04-0c31-11e5-9cbc-9a7517399503.png)
